version: "3.8"

services:
  php:
    image: kinanb/php_pdo_pgsql
    container_name: web_container
    volumes:
      - .:/var/www/html
    ports:
      - "8080:80"

  db:
    image: postgres:9.6.24-alpine3.15
    container_name: database_container
    volumes:
      - ./database:/var/lib/postgresql/data \
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: database

  adminer:
    image: adminer:4.8.1
    container_name: adminer_container
    ports:
      - "8081:8080"
